info:
  name: tasks
  type: folder
  seq: 2

request:
  auth:
    mode: oauth2
    oauth2:
      grantType: authorization_code
      callbackUrl: {{redirect_uri}}
      authorizationUrl: https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/authorize
      accessTokenUrl: https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/token
      client_id: {{client_id}}
      scope: openid profile email offline_access {{api_scope}}
      pkce: true
